language: java

jdk: openjdk8

services:
  - docker
  
before_install:
  - docker run --name=mysql-local -p 3306:3306 -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=db_food -e MYSQL_USER=springUser -e MYSQL_PASSWORD=springPwd --restart on-failure -d mysql/mysql-server:8.0

install: true

cache:
  directories:
  - $HOME/.m2
  
script:
  - mvn -f pom.xml clean verify -Pjacoco,mutation-testing coveralls:report
 