language: java

dist: xenial

jdk: openjdk8
  
addons:
  sonarcloud:
    organization: "em-gei"

install: true

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
  
script:
  - mvn -f pom.xml clean verify sonar:sonar coveralls:report -Pjacoco,mutation-testing