language: java

dist: xenial

matrix:
  include:
    - jdk: openjdk8
    - os: osx
      osx_image: xcode11.5

addons:
  sonarcloud:
    organization: "em-gei"
  apt:
    packages:
      - google-chrome-stable

services:
  - xvfb

install: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

script:
  - mvn -f pom.xml clean verify -Pdocker,mutation-testing,jacoco
  - mvn -f pom.xml verify -Pdocker,e2e-tests
  - mvn -f pom.xml sonar:sonar coveralls:report