version: "2"
services:
  foodinventory-image:
    image: foodinventory-image
    ports:
      - "8080:8080"
    networks:
      - food-mysql
    depends_on:
      - mysql1
 
  mysql1:
    image: mysql:8
    networks:
      - food-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_food
      - MYSQL_USER=springUser
      - MYSQL_PASSWORD=springPwd
      
networks:
  food-mysql: